spring.application.name=spring-security-demo

spring.security.user.name=admin
spring.security.user.password=admin

server.servlet.context-path=/security
server.port = 8000
server.servlet.session.cookie.same-site=strict
