spring.application.name=springjpa
spring.datasource.name=dataSource
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=Neymarjr.10
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true